### PR TITLE
bug: Add failing test for bug caused by casting kernel before launch

### PR DESCRIPTION
**Pull request by johnbowen42**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
The `indirect launcher` test doesn't fail, but we could add this case to that file. Is that what you are suggesting?

**Comment by ggeorgakoudis** [comment]
It doesn't fail because the lit CHECK expressions are crafted to assume that Proteus will not handle indirect launching. We should fix indirect launching and change CHECK expressions to expect 2 (non-cached) Proteus JIT executions for the first run and 2 hits in the storage cache for the second run.

**Comment by davidbeckingsale** [comment]
Got it, thanks for the clarification. I think it would be good to mark expected failure cases more clearly in the tests.

**Comment by ggeorgakoudis** [comment]
I agree, I haven't found a good way to do it with ctest. Marking `WILL_FAIL` will pass the tests when it fails, with no indication in the output that this is an expected failure. Ideally, we would like to test suite to pass but report that some tests fail. Is there a way to do that?

**Comment by ggeorgakoudis** [comment]
Superseded by #36

**Pull request closed without merging**
