### PR TITLE
Fix multiple annotations with RDC

### PR DESCRIPTION
**Pull request by davidbeckingsale**
- Add test `multi_file_launcher`
- Fix by removing overconservative fatal errors

### CODE REVIEW

**Review by ggeorgakoudis — APPROVED** [review]
LGTM

**Comment by koparasy** [comment]
This is kind of weird. I would expect the current implementation of the cache to find the same kernel. As it doesn't account for the translation unit location. Aren't the kernel names of these codes the same?

**Comment by ggeorgakoudis** [comment]
> This is kind of weird. I would expect the current implementation of the cache to find the same kernel. As it doesn't account for the translation unit location. Aren't the kernel names of these codes the same?

The module unique ids by LLVM are different

**Comment by koparasy** [comment]
> > This is kind of weird. I would expect the current implementation of the cache to find the same kernel. As it doesn't account for the translation unit location. Aren't the kernel names of these codes the same?
> 
> The module unique ids by LLVM are different

I don't understand that either. Do these 2 device codes have different external dependencies? I thought the unique id captures the external dependencies of the current translation unit.

**Comment by ggeorgakoudis** [comment]
> > > This is kind of weird. I would expect the current implementation of the cache to find the same kernel. As it doesn't account for the translation unit location. Aren't the kernel names of these codes the same?
> > 
> > 
> > The module unique ids by LLVM are different
> 
> I don't understand that either. Do these 2 device codes have different external dependencies? I thought the unique id captures the external dependencies of the current translation unit.

Check the test, one translation unit will export `main` the other `foo`, results in different module ids

**Comment by koparasy** [comment]
Both foo, and main are cpu codes. Not device. So, do we expect to capture both host and device externals?

**Comment by ggeorgakoudis** [comment]
> Both foo, and main are cpu codes. Not device. So, do we expect to capture both host and device externals?

The rationale is to create a module unique id for the translation unit that includes the kernel. Host code will also have the kernel stub. The module unique id is not ideal anyway and will be removed.

**Pull request merged**
